export const questionsData = [
  {
    id: 1,
    question: "Do you have a project allocated for the brief ?",
    question_type_id: 14,
    question_opt: ["Project name", "No project", "Proactive brief", "Any other"],
    category: 1,
    Category: { id: 1, name: "Overview" },
  },
  {
    id: 2,
    question: "Select Category",
    question_type_id: 3,
    question_opt: ["Fabric Clean (FCL)", "Fabric Enhancer (FEN)", "Home & Hygiene (H&H)", "Add other"],
    category_id: 1,
    Category: { id: 1, name: "Overview" },
  },
  {
    id: 3,
    question: "Select Format",
    question_type_id: 5,
    question_opt: ["Liquid", "Bar", "Powder", "Capsule"],
    category_id: 1,
    Category: { id: 1, name: "Overview" },
  },
  {
    id: 4,
    question: "Select Business Unit",
    question_type_id: 3,
    question_opt: ["Europe", "America", "South Asia", "SEAA"],
    category_id: 1,
    Category: { id: 1, name: "Overview" },
  },
  {
    id: 5,
    question: "Select Country",
    question_type_id: 3,
    question_opt: ["Europe", "America", "South Asia", "SEAA"],
    category_id: 1,
    Category: { id: 1, name: "Overview" },
  },
  {
    id: 6,
    question: "Markets for the projects ",
    question_type_id: 12,
    question_opt: ["Europe", "America", "South Asia", "SEAA"],
    category_id: 1,
    Category: { id: 1, name: "Overview" },
  },
  {
    id: 7,
    question: "What are the expected launch date per market?",
    question_type_id: 12,
    question_opt: null,
    category_id: 1,
    Category: { id: 1, name: "Overview" },
  },
  {
    id: 8,
    question: "Brand position",
    question_type_id: 7,
    question_opt: [
      "brand_sunlight.png",
      "brand_domestos.png",
      "brand_brilhante.png",
      "brand_cif.png",
      "brand_dirtisgood.png",
    ],
    category_id: 1,
    Category: { id: 1, name: "Overview" },
  },
  {
    id: 9,
    question: "Select product cell",
    question_type_id: 13,
    question_opt: [
      "Guardrail",
      "Power House",
      "Unsure",
    ],
    category_id: 1,
    Category: { id: 1, name: "Overview" },
  },
  {
    id: 10,
    question: "What is your business ambition with the project above?\nPlease explain the context of this ambition.",
    question_type_id: 1,
    question_opt: null,
    category_id: 2,
    Category: { id: 2, name: "Section 1" },
  },
  {
    id: 11,
    question: "What role do you expect fragrance to play in achieving the business ambition ?",
    question_type_id: 1,
    question_opt: null,
    category_id: 2,
    Category: { id: 2, name: "Section 1" },
  },
  {
    id: 12,
    question: "Why do you think the current fragrance is not doing the job?",
    question_type_id: 1,
    question_opt: null,
    category_id: 2,
    Category: { id: 2, name: "Section 1" },
  },
  {
    id: 13,
    question: "Before proceeding please confirm you have smelled few in market products along with your CBFMs",
    question_type_id: 15,
    question_opt: ["I confirm"],
    category_id: 2,
    Category: { id: 2, name: "Section 1" },
  },
  {
    id: 14,
    question: "Please outline the specific consumer segment that you intend to influence with the new fragrance",
    question_type_id: 1,
    question_opt: null,
    category_id: 3,
    Category: { id: 3, name: "Section 2" },
  },
  {
    id: 15,
    question: "Describe the experience you wish to give Consumers with the new Fragrance",
    question_type_id: 1,
    question_opt: null,
    category_id: 3,
    Category: { id: 3, name: "Section 2" },
  },
  // {
  //   id: 16,
  //   question: "Select the moments where you would expect the fragrance to do its best",
  //   question_type_id: 8,
  //   question_opt: ["Pre-wash", "During wash", "After wash\n(wet)", "After wash\n(dry)"],
  //   category_id: 3,
  //   Category: { id: 3, name: "Section 2" },
  // },
  {
    id: 17,
    question: "What is the investment you are wanting to make ?",
    question_type_id: 13,
    question_opt: ["Incremental", "At current level", "Below current level"],
    category_id: 4,
    Category: { id: 4, name: "Section 3" },
  },
  {
    id: 18,
    question: "How long do you plan to sustain the investment before expecting an optimization ?",
    question_type_id: 13,
    question_opt: ["Only for launch phase (3 to 6 months)", "Beyond for launch phase (6 to 24 months)", "Any other"],
    category_id: 4,
    Category: { id: 4, name: "Section 3" },
  },
  // {
  //   id: 19,
  //   question: "Describe the experience you wish to give Consumers with the new Fragrance",
  //   question_type_id: 1,
  //   question_opt: null,
  //   category_id: 4,
  //   Category: { id: 4, name: "Section 3" },
  // },
  // {
  //   id: 20,
  //   question: "Specific variant name & high resolution pack shot",
  //   question_type_id: 9,
  //   question_opt: null,
  //   category_id: 4,
  //   Category: { id: 4, name: "Section 3" },
  // },
  // {
  //   id: 21,
  //   question: "Competitive benchmark-name & high resolution pack shot",
  //   question_type_id: 9,
  //   question_opt: null,
  //   category_id: 4,
  //   Category: { id: 4, name: "Section 3" },
  // },
  // {
  //   id: 22,
  //   question: "What is your project concept?",
  //   question_type_id: 9,
  //   question_opt: null,
  //   category_id: 4,
  //   Category: { id: 4, name: "Section 3" },
  // },
  {
    id: 22,
    question: "What are the claims you wish to make, for a new fragrances ?",
    question_type_id: 1,
    question_opt: null,
    category_id: 4,
    Category: { id: 4, name: "Section 3" },
  },
  // {
  //   id: 23,
  //   question: "Do you plan to celebrate this claim within your comms ?",
  //   question_type_id: 8,
  //   question_opt: ["TV", "Digital", "Pack", "Point of sale"],
  //   category_id: 4,
  //   Category: { id: 4, name: "Section 3" },
  // },
]

export const childQuestionData = {
  6: [
    {
      id: 101,
      question: "Lead markets",
      question_type_id: 3,
      question_opt: ["Europe", "America", "South Asia", "SEAA"],
    },
    {
      id: 102,
      question: "Rollout markets",
      question_type_id: 3,
      question_opt: ["Europe", "America", "South Asia", "SEAA"],
    },
    {
      id: 103,
      question: "Impacted markets",
      question_type_id: 3,
      question_opt: ["Europe", "America", "South Asia", "SEAA"],
    },
  ],

  7: [
    {
      id: 104,
      question: "Lead markets",
      question_type_id: 2,
      question_opt: 101,
    },
    {
      id: 105,
      question: "Rollout markets",
      question_type_id: 2,
      question_opt: 102,
    },
    {
      id: 106,
      question: "Impacted markets",
      question_type_id: 2,
      question_opt: 103,
    },
  ],
};