export const questionsData = [
  {
    id: 1,
    question: "Do you have a project allocated for the brief ?",
    question_type_id: 3,
    question_opt: ["Project name", "No project", "Proactive brief", "Any other"],
    category: 1,
    Category: { id: 1, name: "Overview" },
  },
  {
    id: 2,
    question: "Select Category",
    question_type_id: 3,
    question_opt: ["Fabric Clean (FCL)", "Fabric Enhancer (FEN)", "Home & Hygiene (H&H)", "Add other"],
    category_id: 1,
    Category: { id: 1, name: "Overview" },
  },
  {
    id: 3,
    question: "Select Format",
    question_type_id: 5,
    question_opt: ["Liquid", "Bar", "Powder", "Capsule"],
    category_id: 1,
    Category: { id: 1, name: "Overview" },
  },
  {
    id: 4,
    question: "Select Business Unit",
    question_type_id: 3,
    question_opt: ["Europe", "America", "South Asia", "SEAA"],
    category_id: 1,
    Category: { id: 1, name: "Overview" },
  },
  {
    id: 5,
    question: "Select Country",
    question_type_id: 3,
    question_opt: ["Europe", "America", "South Asia", "SEAA"],
    category_id: 1,
    Category: { id: 1, name: "Overview" },
  },
  {
    id: 6,
    question: "Markets for the projects ",
    question_type_id: 12,
    question_opt: ["Europe", "America", "South Asia", "SEAA"],
    category_id: 1,
    Category: { id: 1, name: "Overview" },
  },
  {
    id: 7,
    question: "What are the expected launch date per market?",
    question_type_id: 12,
    question_opt: null,
    category_id: 1,
    Category: { id: 1, name: "Overview" },
  },
  {
    id: 8,
    question: "Brand position",
    question_type_id: 7,
    question_opt: [
      "brand_sunlight.png",
      "brand_domestos.png",
      "brand_brilhante.png",
      "brand_cif.png",
      "brand_dirtisgood.png",
    ],
    category_id: 1,
    Category: { id: 1, name: "Overview" },
  },
  {
    id: 9,
    question: "Select product cell",
    question_type_id: 13,
    question_opt: [
      "Guardrail",
      "Power House",
      "Unsure",
    ],
    category_id: 1,
    Category: { id: 1, name: "Overview" },
  },
  // {
  //   id: 6,
  //   question: "Do you have a project allocated for the brief ?",
  //   question_type_id: "3",
  //   question_opt: ["Project name", "No project", "Proactive brief", "Any other"],
  //   category_id: 2,
  //   Category: { id: 2, name: "Marketing"},
  // },
  // {
  //   id: 7,
  //   question: "Select Category",
  //   question_type_id: "3",
  //   question_opt: ["Fabric Clean (FCL)", "Fabric Enhancer (FEN)", "Home & Hygiene (H&H)", "Add other"],
  //   category_id: 2,
  //   Category: { id: 2, name: "Marketing"},
  // },
  // {
  //   id: 8,
  //   question: "Select Format",
  //   question_type_id: "5",
  //   question_opt: ["Liquid", "Bar", "Powder", "Capsule"],
  //   category_id: 2,
  //   Category: { id: 2, name: "Marketing"},
  // },
  // {
  //   id: 9,
  //   question: "Select Business Unit",
  //   question_type_id: "3",
  //   question_opt: ["Europe", "America", "South Asia", "SEAA"],
  //   category_id: 2,
  //   Category: { id: 2, name: "Marketing"},
  // },
  // {
  //   id: 10,
  //   question: "Select Country",
  //   question_type_id: "3",
  //   question_opt: ["Europe", "America", "South Asia", "SEAA"],
  //   category_id: 2,
  //   Category: { id: 2, name: "Marketing"},
  // },
]

export const childQuestionData = {
  6: [
    {
      id: 101,
      question: "Lead markets",
      question_type_id: 3,
      question_opt: ["Europe", "America", "South Asia", "SEAA"],
    },
    {
      id: 102,
      question: "Rollout markets",
      question_type_id: 3,
      question_opt: ["Europe", "America", "South Asia", "SEAA"],
    },
    {
      id: 103,
      question: "Impacted markets",
      question_type_id: 3,
      question_opt: ["Europe", "America", "South Asia", "SEAA"],
    },
  ],

  7: [
    {
      id: 104,
      question: "Lead markets",
      question_type_id: 2,
      question_opt: 101,
    },
    {
      id: 105,
      question: "Rollout markets",
      question_type_id: 2,
      question_opt: 102,
    },
    {
      id: 106,
      question: "Impacted markets",
      question_type_id: 2,
      question_opt: 103,
    },
  ],
};